### PR TITLE
prep intro guide for docs

### PR DESCRIPTION
**Pull request by grnnja**
To add this guide to the docs, some of the tags need to change from h1's to h2's, and there needs to be a title. When generating the docs before, the h1's would show up as different articles and the title was not correct.

### CODE REVIEW

**Comment by idomic** [comment]
@grnnja please fix conflicts (I did push some updates to the guide, so just take the latest version)

**Comment by grnnja** [comment]
fixed now

btw I noticed that some of the code in the notebook had errors:

image

It looks like its been that way for a few commits

**Comment by edublancas** [comment]
> btw I noticed that some of the code in the notebook had errors:

it's a warning so no worries. please open an issue on the ploomber repository. we are missing a condition here, since this warning should not be triggered under these conditions

**Comment by grnnja** [comment]
Just submitted an issue. https://github.com/ploomber/ploomber/issues/980

It's not on screen, but II thought it might be a problem since the `dag.plot()` doesn't show the plot. It just has the `0%|  ` loading thing. In a previous commit it did show the plot however.

**Comment by edublancas** [comment]
I found a dependency conflict that was breaking the CI for many of the examples, please rebase from the master branch to fix it

**Comment by grnnja** [comment]
Rebased!

**Comment by idomic** [comment]
I think you've missed the reqs.txt in your rebase?

**Comment by grnnja** [comment]
> I think you've missed the reqs.txt in your rebase?

Looks like Eduardo pushed changes. I just rebased again

**Review by idomic — APPROVED** [review]
lgtm

**Pull request merged**
