### PR TITLE
Changed .ipynb files to .html in yaml files

### PR DESCRIPTION
**Pull request by SamBauter**
Related to [ploomber/ploomber Issue #689](https://github.com/ploomber/ploomber/issues/689)

### CODE REVIEW

**Comment by idomic** [comment]
@SamBauter did you run these examples to check it doesn't break?

**Comment by SamBauter** [comment]
I don't believe the examples have been run. This was my first try at contributing to open source (during Pycon 2022 sprints). I'll take a look at it tomorrow and see if I can figure out how to run them to make sure things are working.

**Comment by idomic** [comment]
No problem, thanks for letting me know and your contribution, we'll take it
from here :)
Maybe doc edits will be easier for the first steps.

**Comment by 94rain** [comment]
Thanks for your work. Could you update guides/parametrized/pipeline.yaml as well?
https://github.com/SamBauter/projects/blob/fdea9796e6b88f574c0f7c577661351d233c1708/guides/parametrized/pipeline.yaml#L5

I am working on running these examples to make sure things are working.

**Comment by 94rain** [comment]
Progress:

Working examples: (Original file / updated file)
* cloud-execution: OK / OK
* cron: OK / OK
* first-pipeline: OK / OK
* monitoring: OK / OK
* parametrized: OK / OK

TODO:
* debugging:  Needs some edits
* logging: ploomber build: error: Unable to find a pipeline
* refactor: ploomber build: error: Unable to find a pipeline
* serialization: ploomber build: error: Unable to find a pipeline
* sql-templating: Failed
* testing: Failed
* versioning: ploomber build: error: Unable to find a pipeline

**Comment by 94rain** [comment]
I don't have write access to @SamBauter's repos. Only they are able to change it.

**Comment by SamBauter** [comment]
fixing now

**Comment by SamBauter** [comment]
sent a collaboration invitation to my forked repo. I think it will give you push access

**Comment by 94rain** [comment]
> sent a collaboration invitation to my forked repo. I think it will give you push access

Updated. Thanks!

**Comment by 94rain** [comment]
Progress:

* cloud-execution: OK
* cron: OK
* first-pipeline: OK
* monitoring: OK
* parametrized: OK
* logging: basic OK parametrized OK
* refactor: ipynb runs smoothly
* serialization: ipynb runs smoothly
* sql-templating: ipynb runs smoothly
* testing: ipynb runs smoothly
* versioning: ipynb runs smoothly
* debugging:  seems intentionally broken

Seems all working!

**Comment by idomic** [comment]
@94rain I've tested 2 notebooks and it seems like they're working. 

We should also change the README.ipynb themselves (in it we present the `pipeline.yaml` in the `Pipeline declaration` section) and currently it's not up to date, you can change it manually or run the script that does it for you.

**Comment by idomic** [comment]
@94rain I've tested 2 notebooks and it seems like they're working. 

We should also change the README.ipynb themselves (in it we present the `pipeline.yaml` in the `Pipeline declaration` section) and currently it's not up to date, you can change it manually or run the script that does it for you.

**Comment by 94rain** [comment]
> @94rain I've tested 2 notebooks and it seems like they're working.
> 
> We should also change the README.ipynb themselves (in it we present the `pipeline.yaml` in the `Pipeline declaration` section) and currently it's not up to date, you can change it manually or run the script that does it for you.

All updated except the colab example (to avoid merge conflict). I will update the colab example in another PR.

**Comment by idomic** [comment]
LGTM, great job!
Thanks for contributing @SamBauter @94rain

**Comment by edublancas** [comment]
this PR broke the CI: https://github.com/ploomber/projects/runs/6804657637?check_suite_focus=true

the problem doesn't seem to be related to the changes, but rather to an API breaking change in seaborn

**Pull request merged**
