### PR TITLE
Update colab example for installing from locked requirements file

### PR DESCRIPTION
**Pull request by 94rain**
## Describe your changes
Added the following at the top of colab example
```
!echo Installing packages with fixed versions for colab
!pip -q install -r https://github.com/ploomber/ploomber/raw/master/requirements-colab.lock.txt
```
Before ploomber/ploomber#786 is merged, for testing purpose, we can run `!pip -q install -r https://raw.githubusercontent.com/ploomber/ploomber/c8e55d4da942b5ddeba178e603ea55be7054750e/requirements-colab.lock.txt` instead

## Issue ticket number and link
Part of ploomber/ploomber#786. Along with ploomber/ploomber#836, these two PRs closes ploomber/ploomber#786

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by idomic** [comment]
@94rain please also re-enable the colab as part of the main readme (it was removed in an earlier commit).
Also, we can remove the pygraphviz install from the top of the notebook (to speed things up) and replace those image plots:
```
from IPython.display import Image
Image(filename='pipeline.png')
```
 with:

```
from IPython.display import HTML, IFrame
IFrame(src='pipeline.html', width=700, height=600)
display(HTML('pipeline.html')) # Either HTML or IFrame should work
```

Just make sure the resolution makes sense so the users don't have to scroll.

**Comment by idomic** [comment]
Also, please double check it works with the updated colab.reqs.txt, our dependencies bot complained on security risks and upgraded some of the package versions in it.

**Comment by 94rain** [comment]
So we can remove all of these after updating the image plots part?
```
!echo Installing pygraphviz
!sudo apt-get -q update -y
!sudo apt-get -q install -y graphviz graphviz-dev
!pip -q install graphviz 'pygraphviz<1.8'
```

**Comment by 94rain** [comment]
> re-enable the colab as part of the main readme

https://github.com/ploomber/ploomber/commit/02c3e8a97a6865a3d74a37950d6f7c02952dc004
Looks like it was removed from the ploomber repo. Do we want to add the colab example to `ploomber` or `projects` repo, or both? For the ploomber repo I can just undo that commit. For the projects repo I can add a subsection `Use Colab` before `Use Binder`.

> please double check it works with the updated colab.reqs.txt

I just double-checked that it still works. Also, the bootstrap time should be no more than 30 seconds now. Updated accordingly.

> Just make sure the resolution makes sense so the users don't have to scroll.

There may not be an easy way to resize with HTML. Iframe seems not working. I am looking into this.

**Comment by 94rain** [comment]
Unfortunately colab does not seem to support iframe. The iframe content is put to `https://localhost:8080/pipeline.html`. There seems no solution to this but to use HTML instead.

* https://stackoverflow.com/questions/59091645/serving-an-iframe-in-google-colab-notebook-localhost-refused-to-connect (recommended using HTML instead)
* https://stackoverflow.com/questions/62407194/error-localhost-refused-to-connect-when-loading-background-map-from-osmnx-fol (unanswered)

**Comment by idomic** [comment]
No problem, let's use HTML here, is there any way we can scale it down a
bit? It seems we need to scroll a lot to see all of the graph.

**Comment by 94rain** [comment]
The HTML output seems to be missing the output file paths. Is that expected?

pygraphviz output:
image

HTML output:
image

**Comment by idomic** [comment]
@94rain Yes it's an upgrade we did to make it more readable

**Comment by idomic** [comment]
Well the HTML works on Colab and IFrame doesn't, it might be a different
scenario on a regular jupyter notebook instance (since colab is kind of a
black box).

**Comment by 94rain** [comment]
> let's take the css approach, inject it from within the cell

What do you mean by "inject it from within the cell"? I tried things like `HTML("<style>...</style>" + embed("pipeline.html"))` (psedocode) but does not seem to work. We might need to change the HTML directly.

**Comment by 94rain** [comment]
The resolution issue should now be resolved by updating the scale to 50% in the dag teamplate.

**Review by idomic — COMMENTED** [review]
lgtm

**Pull request merged**
